name: Jeffrey R. Heeter
favicon: null
layout_spectrum: 0.6898109999019653
typography_spectrum: 0.9606754281558096
title: Jeffrey R. Heeter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a2a2c'
    - '#b73f40'
    - '#616161'
    - '#a9a9a9'
  brandStrength: 0
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0
purpose: []
